---
title: "' <typename> System. Exception ' veya ' System. Exception ' öğesinden devralan bir sınıf olmadığından ' catch ', ' ' türünü yakalayamaz"
ms.date: 07/20/2015
f1_keywords:
- vbc30392
- bc30392
helpviewer_keywords:
- BC30392
ms.assetid: 1d513d1d-38f5-4b4e-95bb-9f1209553803
ms.openlocfilehash: 9a309896fa66e657319d98d127221cccc6f0488d
ms.sourcegitcommit: bf5c5850654187705bc94cc40ebfb62fe346ab02
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 09/23/2020
ms.locfileid: "91082226"
---
# <a name="catch-cannot-catch-type-typename-because-it-is-not-systemexception-or-a-class-that-inherits-from-systemexception"></a>' \<typename> System. Exception ' veya ' System. Exception ' öğesinden devralan bir sınıf olmadığından ' catch ', ' ' türünü yakalayamaz

`Catch` yalnızca özel durumları ele geçirebilir ve bir özel durumdan türetilmeyen bir şeyi yakalamaya çalıştınız.  
  
 **Hata kimliği:** BC30392  
  
## <a name="to-correct-this-error"></a>Bu hatayı düzeltmek için  
  
1. İfadesini kaldırın `Catch` veya hedefini `Catch` gerçek bir özel durumla değiştirin.  
  
## <a name="see-also"></a>Ayrıca bkz.

- [Try...Catch...Finally Deyimi](../language-reference/statements/try-catch-finally-statement.md)
