---
description: "Daha fazla bilgi edinin: ' ', ' ' <name1> öğesinden devralındığından ' catch ' bloğuna hiç ulaşılamadı <name2>"
title: "' ', ' ' <name1> Öğesinden devraldığından ' catch ' bloğuna hiç ulaşılamadı. <name2>"
ms.date: 07/20/2015
f1_keywords:
- BC42029
- vbc42029
helpviewer_keywords:
- BC42029
ms.assetid: 4bc84a84-ec7e-49db-8794-4fb71d36d5c0
ms.openlocfilehash: 9fbbad2d11f261f68ad1e4f63cb691805d59995e
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 02/14/2021
ms.locfileid: "100422763"
---
# <a name="catch-block-never-reached-because-name1-inherits-from-name2"></a>' ', ' ' \<name1> Öğesinden devraldığından ' catch ' bloğuna hiç ulaşılamadı. \<name2>

`Catch`Kod içindeki bir bloğa hiç ulaşılamadı.  
  
 Bu ileti, varsayılan olarak bir uyarıdır. Uyarıları gizleme veya uyarıları hata olarak değerlendirme hakkında daha fazla bilgi için bkz. [Visual Basic uyarıları yapılandırma](/visualstudio/ide/configuring-warnings-in-visual-basic).  
  
 **Hata kimliği:** BC42029  
  
## <a name="to-correct-this-error"></a>Bu hatayı düzeltmek için  
  
- Yabancı bloğu kaldırın `Catch` .  
  
## <a name="see-also"></a>Ayrıca bkz.

- [Özel durumları yakalamak için try/catch bloğunu kullanma](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [Try...Catch...Finally Deyimi](../language-reference/statements/try-catch-finally-statement.md)
