---
title: Özel durumlar ve özel durum Işleme-C# Programlama Kılavuzu
description: Özel durumlar ve özel durum işleme hakkında bilgi edinin. Bu C# özellikleri, bir program çalışırken gerçekleşen beklenmedik veya olağanüstü durumlarla başa çıkmanıza yardımcı olur.
ms.date: 12/09/2020
helpviewer_keywords:
- exception handling [C#]
- exceptions [C#]
- C# language, exceptions
ms.assetid: 0001887f-4fa2-47e2-8034-2819477e2344
ms.openlocfilehash: 245299707254c7bafb4589ee8031a107921ca2a7
ms.sourcegitcommit: e7e0921d0a10f85e9cb12f8b87cc1639a6c8d3fe
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 04/09/2021
ms.locfileid: "107255408"
---
# <a name="exceptions-and-exception-handling-c-programming-guide"></a><span data-ttu-id="1016d-104">Özel Durumlar ve Özel Durum İşleme (C# Programlama Kılavuzu)</span><span class="sxs-lookup"><span data-stu-id="1016d-104">Exceptions and Exception Handling (C# Programming Guide)</span></span>

<span data-ttu-id="1016d-105">C# dilinin özel durum işleme özellikleri, bir program çalışırken oluşan beklenmedik veya olağanüstü durumlarla ilgilenmenize yardımcı olur.</span><span class="sxs-lookup"><span data-stu-id="1016d-105">The C# language's exception handling features help you deal with any unexpected or exceptional situations that occur when a program is running.</span></span> <span data-ttu-id="1016d-106">Özel durum işleme `try` , `catch` başarılı olmayan eylemleri denemek için,, ve anahtar kelimelerini kullanır, bu `finally` işlemin ne kadar uygun olduğuna karar verirken sorunları işleyebilir ve kaynakları daha sonra temizleyebiliriz.</span><span class="sxs-lookup"><span data-stu-id="1016d-106">Exception handling uses the `try`, `catch`, and `finally` keywords to try actions that may not succeed, to handle failures when you decide that it's reasonable to do so, and to clean up resources afterward.</span></span> <span data-ttu-id="1016d-107">Özel durumlar ortak dil çalışma zamanı (CLR), .NET veya üçüncü taraf kitaplıkları tarafından veya uygulama kodu tarafından oluşturulabilir.</span><span class="sxs-lookup"><span data-stu-id="1016d-107">Exceptions can be generated by the common language runtime (CLR), by .NET or third-party libraries, or by application code.</span></span> <span data-ttu-id="1016d-108">Özel durumlar anahtar sözcüğü kullanılarak oluşturulur `throw` .</span><span class="sxs-lookup"><span data-stu-id="1016d-108">Exceptions are created by using the `throw` keyword.</span></span>

<span data-ttu-id="1016d-109">Çoğu durumda, kodunuzun doğrudan çağırdığı bir yöntem tarafından değil, çağrı yığınında daha sonra başka bir yöntem tarafından bir özel durum atılır.</span><span class="sxs-lookup"><span data-stu-id="1016d-109">In many cases, an exception may be thrown not by a method that your code has called directly, but by another method further down in the call stack.</span></span> <span data-ttu-id="1016d-110">Bir özel durum oluştuğunda, CLR, belirli bir özel durum türü için blok içeren bir yöntemi arayarak yığını yeniden aşağı doğru `catch` çalıştırır ve bulduğu ilk bu `catch` blok yürütülür.</span><span class="sxs-lookup"><span data-stu-id="1016d-110">When an exception is thrown, the CLR will unwind the stack, looking for a method with a `catch` block for the specific exception type, and it will execute the first such `catch` block that if finds.</span></span> <span data-ttu-id="1016d-111">`catch`Çağrı yığınında herhangi bir yerde uygun bir blok bulmaz, işlemi sonlandırır ve kullanıcıya bir ileti görüntüler.</span><span class="sxs-lookup"><span data-stu-id="1016d-111">If it finds no appropriate `catch` block anywhere in the call stack, it will terminate the process and display a message to the user.</span></span>

<span data-ttu-id="1016d-112">Bu örnekte, bir yöntem sıfıra bölme için test eder ve hatayı yakalar.</span><span class="sxs-lookup"><span data-stu-id="1016d-112">In this example, a method tests for division by zero and catches the error.</span></span> <span data-ttu-id="1016d-113">Özel durum işleme olmadan, bu program bir **Dividebysıfırlaması özel durumu** ile sonlandırılır ve işlenmemiş bir hatadır.</span><span class="sxs-lookup"><span data-stu-id="1016d-113">Without the exception handling, this program would terminate with a **DivideByZeroException was unhandled** error.</span></span>

:::code language="csharp" source="snippets/exceptions/ExceptionTest.cs" ID="ExceptionTest":::

## <a name="exceptions-overview"></a><span data-ttu-id="1016d-114">Özel durumlara genel bakış</span><span class="sxs-lookup"><span data-stu-id="1016d-114">Exceptions Overview</span></span>

<span data-ttu-id="1016d-115">Özel durumlar aşağıdaki özelliklere sahiptir:</span><span class="sxs-lookup"><span data-stu-id="1016d-115">Exceptions have the following properties:</span></span>

- <span data-ttu-id="1016d-116">Özel durumlar, tüm sonunda türetilen türlerdir `System.Exception` .</span><span class="sxs-lookup"><span data-stu-id="1016d-116">Exceptions are types that all ultimately derive from `System.Exception`.</span></span>
- <span data-ttu-id="1016d-117">`try`Özel durumlar oluşturabilecek deyimler etrafında bir blok kullanın.</span><span class="sxs-lookup"><span data-stu-id="1016d-117">Use a `try` block around the statements that might throw exceptions.</span></span>
- <span data-ttu-id="1016d-118">Blokta bir özel durum oluştuktan sonra `try` Denetim akışı, çağrı yığınında herhangi bir yerde bulunan ilk ilişkili özel durum işleyicisine atlar.</span><span class="sxs-lookup"><span data-stu-id="1016d-118">Once an exception occurs in the `try` block, the flow of control jumps to the first associated exception handler that is present anywhere in the call stack.</span></span> <span data-ttu-id="1016d-119">C# ' de, `catch` bir özel durum işleyicisini tanımlamak için anahtar sözcüğü kullanılır.</span><span class="sxs-lookup"><span data-stu-id="1016d-119">In C#, the `catch` keyword is used to define an exception handler.</span></span>
- <span data-ttu-id="1016d-120">Belirli bir özel durum için özel durum işleyicisi yoksa, program yürütmeyi bir hata iletisiyle sonlandırır.</span><span class="sxs-lookup"><span data-stu-id="1016d-120">If no exception handler for a given exception is present, the program stops executing with an error message.</span></span>
- <span data-ttu-id="1016d-121">Bunu işleyebilmediğiniz ve uygulamayı bilinen bir durumda bırakarak bir özel durum yakalamayın.</span><span class="sxs-lookup"><span data-stu-id="1016d-121">Don't catch an exception unless you can handle it and leave the application in a known state.</span></span> <span data-ttu-id="1016d-122">Yakalar `System.Exception` , `throw` bloğunun sonundaki anahtar sözcüğünü kullanarak yeniden oluşturun `catch` .</span><span class="sxs-lookup"><span data-stu-id="1016d-122">If you catch `System.Exception`, rethrow it using the `throw` keyword at the end of the `catch` block.</span></span>
- <span data-ttu-id="1016d-123">Bir `catch` blok bir özel durum değişkeni tanımlıyorsa, oluşan özel durum türü hakkında daha fazla bilgi edinmek için onu kullanabilirsiniz.</span><span class="sxs-lookup"><span data-stu-id="1016d-123">If a `catch` block defines an exception variable, you can use it to obtain more information about the type of exception that occurred.</span></span>
- <span data-ttu-id="1016d-124">Özel durumlar, anahtar sözcüğü kullanılarak bir program tarafından açıkça oluşturulabilir `throw` .</span><span class="sxs-lookup"><span data-stu-id="1016d-124">Exceptions can be explicitly generated by a program by using the `throw` keyword.</span></span>
- <span data-ttu-id="1016d-125">Özel durum nesneleri, hata hakkında, çağrı yığınının durumu ve hatanın metin açıklaması gibi ayrıntılı bilgiler içerir.</span><span class="sxs-lookup"><span data-stu-id="1016d-125">Exception objects contain detailed information about the error, such as the state of the call stack and a text description of the error.</span></span>
- <span data-ttu-id="1016d-126">Bir `finally` özel durum oluşsa bile bloktaki kod yürütülür.</span><span class="sxs-lookup"><span data-stu-id="1016d-126">Code in a `finally` block is executed even if an exception is thrown.</span></span> <span data-ttu-id="1016d-127">Kaynakları serbest bırakmak için bir `finally` blok kullanın, örneğin, bloğunda açılan tüm akışları veya dosyaları kapatmak `try` .</span><span class="sxs-lookup"><span data-stu-id="1016d-127">Use a `finally` block to release resources, for example to close any streams or files that were opened in the `try` block.</span></span>
- <span data-ttu-id="1016d-128">.NET 'teki yönetilen özel durumlar, Win32 yapılandırılmış özel durum işleme mekanizmasının üzerine uygulanır.</span><span class="sxs-lookup"><span data-stu-id="1016d-128">Managed exceptions in .NET are implemented on top of the Win32 structured exception handling mechanism.</span></span> <span data-ttu-id="1016d-129">Daha fazla bilgi için, bkz. [yapılandırılmış özel durum işleme (C/C++)](/cpp/cpp/structured-exception-handling-c-cpp) ve [Win32 yapılandırılmış özel durum işleme derinlikleri üzerinde çökme kursu](http://bytepointer.com/resources/pietrek_crash_course_depths_of_win32_seh.htm).</span><span class="sxs-lookup"><span data-stu-id="1016d-129">For more information, see [Structured Exception Handling (C/C++)](/cpp/cpp/structured-exception-handling-c-cpp) and [A Crash Course on the Depths of Win32 Structured Exception Handling](http://bytepointer.com/resources/pietrek_crash_course_depths_of_win32_seh.htm).</span></span>

## <a name="c-language-specification"></a><span data-ttu-id="1016d-130">C# Dil Belirtimi</span><span class="sxs-lookup"><span data-stu-id="1016d-130">C# Language Specification</span></span>

<span data-ttu-id="1016d-131">Daha fazla bilgi için bkz. [C# dil belirtiminde](/dotnet/csharp/language-reference/language-specification/introduction) [özel durumlar](~/_csharplang/spec/exceptions.md) .</span><span class="sxs-lookup"><span data-stu-id="1016d-131">For more information, see [Exceptions](~/_csharplang/spec/exceptions.md) in the [C# Language Specification](/dotnet/csharp/language-reference/language-specification/introduction).</span></span> <span data-ttu-id="1016d-132">Dil belirtimi, C# sözdizimi ve kullanımı için kesin bir kaynaktır.</span><span class="sxs-lookup"><span data-stu-id="1016d-132">The language specification is the definitive source for C# syntax and usage.</span></span>

## <a name="see-also"></a><span data-ttu-id="1016d-133">Ayrıca bkz.</span><span class="sxs-lookup"><span data-stu-id="1016d-133">See also</span></span>

- <xref:System.SystemException>
- [<span data-ttu-id="1016d-134">C# anahtar sözcükleri</span><span class="sxs-lookup"><span data-stu-id="1016d-134">C# Keywords</span></span>](../../language-reference/keywords/index.md)
- [<span data-ttu-id="1016d-135">throw</span><span class="sxs-lookup"><span data-stu-id="1016d-135">throw</span></span>](../../language-reference/keywords/throw.md)
- [<span data-ttu-id="1016d-136">try-catch</span><span class="sxs-lookup"><span data-stu-id="1016d-136">try-catch</span></span>](../../language-reference/keywords/try-catch.md)
- [<span data-ttu-id="1016d-137">try-finally</span><span class="sxs-lookup"><span data-stu-id="1016d-137">try-finally</span></span>](../../language-reference/keywords/try-finally.md)
- [<span data-ttu-id="1016d-138">try-catch-finally</span><span class="sxs-lookup"><span data-stu-id="1016d-138">try-catch-finally</span></span>](../../language-reference/keywords/try-catch-finally.md)
- [<span data-ttu-id="1016d-139">Özel durumlar</span><span class="sxs-lookup"><span data-stu-id="1016d-139">Exceptions</span></span>](../../../standard/exceptions/index.md)
