---
title: Özel durumlar ve özel durum Işleme-C# Programlama Kılavuzu
ms.date: 07/20/2015
helpviewer_keywords:
- exception handling [C#]
- exceptions [C#]
- C# language, exceptions
ms.assetid: 0001887f-4fa2-47e2-8034-2819477e2344
ms.openlocfilehash: 0ba123fa9f9aacd0876f07bdf3ae7bb9159a6834
ms.sourcegitcommit: a241301495a84cc8c64fe972330d16edd619868b
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 06/01/2020
ms.locfileid: "84241714"
---
# <a name="exceptions-and-exception-handling-c-programming-guide"></a><span data-ttu-id="ff8d5-102">Özel Durumlar ve Özel Durum İşleme (C# Programlama Kılavuzu)</span><span class="sxs-lookup"><span data-stu-id="ff8d5-102">Exceptions and Exception Handling (C# Programming Guide)</span></span>

<span data-ttu-id="ff8d5-103">C# dilinin özel durum işleme özellikleri, bir program çalışırken oluşan beklenmedik veya olağanüstü durumlarla ilgilenmenize yardımcı olur.</span><span class="sxs-lookup"><span data-stu-id="ff8d5-103">The C# language's exception handling features help you deal with any unexpected or exceptional situations that occur when a program is running.</span></span> <span data-ttu-id="ff8d5-104">Özel durum işleme `try` , `catch` başarılı olmayan eylemleri denemek için,, ve anahtar kelimelerini kullanır, bunu yapmak için `finally` makul olduğuna karar verirken sorunları işleyebilir ve kaynakları daha sonra temizleyebiliriz.</span><span class="sxs-lookup"><span data-stu-id="ff8d5-104">Exception handling uses the `try`, `catch`, and `finally` keywords to try actions that may not succeed, to handle failures when you decide that it is reasonable to do so, and to clean up resources afterward.</span></span> <span data-ttu-id="ff8d5-105">Özel durumlar ortak dil çalışma zamanı (CLR), .NET veya üçüncü taraf kitaplıkları tarafından veya uygulama kodu tarafından oluşturulabilir.</span><span class="sxs-lookup"><span data-stu-id="ff8d5-105">Exceptions can be generated by the common language runtime (CLR), by .NET or third-party libraries, or by application code.</span></span> <span data-ttu-id="ff8d5-106">Özel durumlar anahtar sözcüğü kullanılarak oluşturulur `throw` .</span><span class="sxs-lookup"><span data-stu-id="ff8d5-106">Exceptions are created by using the `throw` keyword.</span></span>

<span data-ttu-id="ff8d5-107">Çoğu durumda, kodunuzun doğrudan çağırdığı bir yöntem tarafından değil, çağrı yığınında daha sonra başka bir yöntem tarafından bir özel durum atılır.</span><span class="sxs-lookup"><span data-stu-id="ff8d5-107">In many cases, an exception may be thrown not by a method that your code has called directly, but by another method further down in the call stack.</span></span> <span data-ttu-id="ff8d5-108">Bu durumda, CLR, belirli bir özel durum türü için blok içeren bir yöntemi arayarak yığını geriye doğru `catch` yürütür ve `catch` bulursa bu blok üzerinde yürütülür.</span><span class="sxs-lookup"><span data-stu-id="ff8d5-108">When this happens, the CLR will unwind the stack, looking for a method with a `catch` block for the specific exception type, and it will execute the first such `catch` block that if finds.</span></span> <span data-ttu-id="ff8d5-109">`catch`Çağrı yığınında herhangi bir yerde uygun bir blok bulmaz, işlemi sonlandırır ve kullanıcıya bir ileti görüntüler.</span><span class="sxs-lookup"><span data-stu-id="ff8d5-109">If it finds no appropriate `catch` block anywhere in the call stack, it will terminate the process and display a message to the user.</span></span>

<span data-ttu-id="ff8d5-110">Bu örnekte, bir yöntem sıfıra bölme için test eder ve hatayı yakalar.</span><span class="sxs-lookup"><span data-stu-id="ff8d5-110">In this example, a method tests for division by zero and catches the error.</span></span> <span data-ttu-id="ff8d5-111">Özel durum işleme olmadan, bu program bir **Dividebysıfırlaması özel durumu** ile sonlandırılır ve işlenmemiş bir hatadır.</span><span class="sxs-lookup"><span data-stu-id="ff8d5-111">Without the exception handling, this program would terminate with a **DivideByZeroException was unhandled** error.</span></span>

[!code-csharp[csProgGuideExceptions#18](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#18)]

## <a name="exceptions-overview"></a><span data-ttu-id="ff8d5-112">Özel durumlara genel bakış</span><span class="sxs-lookup"><span data-stu-id="ff8d5-112">Exceptions Overview</span></span>

<span data-ttu-id="ff8d5-113">Özel durumlar aşağıdaki özelliklere sahiptir:</span><span class="sxs-lookup"><span data-stu-id="ff8d5-113">Exceptions have the following properties:</span></span>

- <span data-ttu-id="ff8d5-114">Özel durumlar, tüm sonunda türetilen türlerdir `System.Exception` .</span><span class="sxs-lookup"><span data-stu-id="ff8d5-114">Exceptions are types that all ultimately derive from `System.Exception`.</span></span>
- <span data-ttu-id="ff8d5-115">`try`Özel durumlar oluşturabilecek deyimler etrafında bir blok kullanın.</span><span class="sxs-lookup"><span data-stu-id="ff8d5-115">Use a `try` block around the statements that might throw exceptions.</span></span>
- <span data-ttu-id="ff8d5-116">Blokta bir özel durum oluştuktan sonra `try` Denetim akışı, çağrı yığınında herhangi bir yerde bulunan ilk ilişkili özel durum işleyicisine atlar.</span><span class="sxs-lookup"><span data-stu-id="ff8d5-116">Once an exception occurs in the `try` block, the flow of control jumps to the first associated exception handler that is present anywhere in the call stack.</span></span> <span data-ttu-id="ff8d5-117">C# ' de, `catch` bir özel durum işleyicisini tanımlamak için anahtar sözcüğü kullanılır.</span><span class="sxs-lookup"><span data-stu-id="ff8d5-117">In C#, the `catch` keyword is used to define an exception handler.</span></span>
- <span data-ttu-id="ff8d5-118">Belirli bir özel durum için özel durum işleyicisi yoksa, program yürütmeyi bir hata iletisiyle sonlandırır.</span><span class="sxs-lookup"><span data-stu-id="ff8d5-118">If no exception handler for a given exception is present, the program stops executing with an error message.</span></span>
- <span data-ttu-id="ff8d5-119">İşleyebilmediğiniz ve uygulamayı bilinen bir durumda bırakarak bir özel durumu yakalamayın.</span><span class="sxs-lookup"><span data-stu-id="ff8d5-119">Do not catch an exception unless you can handle it and leave the application in a known state.</span></span> <span data-ttu-id="ff8d5-120">Yakalar `System.Exception` , `throw` bloğunun sonundaki anahtar sözcüğünü kullanarak yeniden oluşturun `catch` .</span><span class="sxs-lookup"><span data-stu-id="ff8d5-120">If you catch `System.Exception`, re-throw it using the `throw` keyword at the end of the `catch` block.</span></span>
- <span data-ttu-id="ff8d5-121">Bir `catch` blok bir özel durum değişkeni tanımlıyorsa, oluşan özel durum türü hakkında daha fazla bilgi edinmek için onu kullanabilirsiniz.</span><span class="sxs-lookup"><span data-stu-id="ff8d5-121">If a `catch` block defines an exception variable, you can use it to obtain more information about the type of exception that occurred.</span></span>
- <span data-ttu-id="ff8d5-122">Özel durumlar, anahtar sözcüğü kullanılarak bir program tarafından açıkça oluşturulabilir `throw` .</span><span class="sxs-lookup"><span data-stu-id="ff8d5-122">Exceptions can be explicitly generated by a program by using the `throw` keyword.</span></span>
- <span data-ttu-id="ff8d5-123">Özel durum nesneleri, hata hakkında, çağrı yığınının durumu ve hatanın metin açıklaması gibi ayrıntılı bilgiler içerir.</span><span class="sxs-lookup"><span data-stu-id="ff8d5-123">Exception objects contain detailed information about the error, such as the state of the call stack and a text description of the error.</span></span>
- <span data-ttu-id="ff8d5-124">Bir `finally` özel durum oluşsa bile bloktaki kod yürütülür.</span><span class="sxs-lookup"><span data-stu-id="ff8d5-124">Code in a `finally` block is executed even if an exception is thrown.</span></span> <span data-ttu-id="ff8d5-125">Kaynakları serbest bırakmak için bir `finally` blok kullanın, örneğin, bloğunda açılan tüm akışları veya dosyaları kapatmak `try` .</span><span class="sxs-lookup"><span data-stu-id="ff8d5-125">Use a `finally` block to release resources, for example to close any streams or files that were opened in the `try` block.</span></span>
- <span data-ttu-id="ff8d5-126">.NET 'teki yönetilen özel durumlar, Win32 yapılandırılmış özel durum işleme mekanizmasının üzerine uygulanır.</span><span class="sxs-lookup"><span data-stu-id="ff8d5-126">Managed exceptions in .NET are implemented on top of the Win32 structured exception handling mechanism.</span></span> <span data-ttu-id="ff8d5-127">Daha fazla bilgi için, bkz. [yapılandırılmış özel durum işleme (C/C++)](/cpp/cpp/structured-exception-handling-c-cpp) ve [Win32 yapılandırılmış özel durum işleme derinlikleri üzerinde çökme kursu](http://bytepointer.com/resources/pietrek_crash_course_depths_of_win32_seh.htm).</span><span class="sxs-lookup"><span data-stu-id="ff8d5-127">For more information, see [Structured Exception Handling (C/C++)](/cpp/cpp/structured-exception-handling-c-cpp) and [A Crash Course on the Depths of Win32 Structured Exception Handling](http://bytepointer.com/resources/pietrek_crash_course_depths_of_win32_seh.htm).</span></span>

## <a name="related-sections"></a><span data-ttu-id="ff8d5-128">İlgili Bölümler</span><span class="sxs-lookup"><span data-stu-id="ff8d5-128">Related Sections</span></span>

<span data-ttu-id="ff8d5-129">Özel durumlar ve özel durum işleme hakkında daha fazla bilgi için aşağıdaki makalelere bakın:</span><span class="sxs-lookup"><span data-stu-id="ff8d5-129">See the following articles for more information about exceptions and exception handling:</span></span>

- [<span data-ttu-id="ff8d5-130">Özel Durumlar Kullanma</span><span class="sxs-lookup"><span data-stu-id="ff8d5-130">Using Exceptions</span></span>](using-exceptions.md)
- [<span data-ttu-id="ff8d5-131">Özel Durum İşleme</span><span class="sxs-lookup"><span data-stu-id="ff8d5-131">Exception Handling</span></span>](exception-handling.md)
- [<span data-ttu-id="ff8d5-132">Özel Durumlar Oluşturma ve Atma</span><span class="sxs-lookup"><span data-stu-id="ff8d5-132">Creating and Throwing Exceptions</span></span>](creating-and-throwing-exceptions.md)
- [<span data-ttu-id="ff8d5-133">Derleyicinin Ürettiği Özel Durumlar</span><span class="sxs-lookup"><span data-stu-id="ff8d5-133">Compiler-Generated Exceptions</span></span>](compiler-generated-exceptions.md)
- [<span data-ttu-id="ff8d5-134">Try/catch kullanarak özel durum işleme (C# Programlama Kılavuzu)</span><span class="sxs-lookup"><span data-stu-id="ff8d5-134">How to handle an exception using try/catch (C# Programming Guide)</span></span>](how-to-handle-an-exception-using-try-catch.md)
- [<span data-ttu-id="ff8d5-135">Finally anahtar sözcüğünü kullanarak temizleme kodu yürütme</span><span class="sxs-lookup"><span data-stu-id="ff8d5-135">How to execute cleanup code using finally</span></span>](how-to-execute-cleanup-code-using-finally.md)
- [<span data-ttu-id="ff8d5-136">CLS dışı özel durumu yakalama</span><span class="sxs-lookup"><span data-stu-id="ff8d5-136">How to catch a non-CLS exception</span></span>](how-to-catch-a-non-cls-exception.md)

## <a name="c-language-specification"></a><span data-ttu-id="ff8d5-137">C# Dil Belirtimi</span><span class="sxs-lookup"><span data-stu-id="ff8d5-137">C# Language Specification</span></span>

<span data-ttu-id="ff8d5-138">Daha fazla bilgi için bkz. [C# dil belirtiminde](/dotnet/csharp/language-reference/language-specification/introduction) [özel durumlar](~/_csharplang/spec/exceptions.md) .</span><span class="sxs-lookup"><span data-stu-id="ff8d5-138">For more information, see [Exceptions](~/_csharplang/spec/exceptions.md) in the [C# Language Specification](/dotnet/csharp/language-reference/language-specification/introduction).</span></span> <span data-ttu-id="ff8d5-139">Dil belirtimi, C# sözdizimi ve kullanımı için kesin bir kaynaktır.</span><span class="sxs-lookup"><span data-stu-id="ff8d5-139">The language specification is the definitive source for C# syntax and usage.</span></span>

## <a name="see-also"></a><span data-ttu-id="ff8d5-140">Ayrıca bkz.</span><span class="sxs-lookup"><span data-stu-id="ff8d5-140">See also</span></span>

- <xref:System.SystemException>
- [<span data-ttu-id="ff8d5-141">C# Programlama Kılavuzu</span><span class="sxs-lookup"><span data-stu-id="ff8d5-141">C# Programming Guide</span></span>](../index.md)
- [<span data-ttu-id="ff8d5-142">C# anahtar sözcükleri</span><span class="sxs-lookup"><span data-stu-id="ff8d5-142">C# Keywords</span></span>](../../language-reference/keywords/index.md)
- [<span data-ttu-id="ff8d5-143">throw</span><span class="sxs-lookup"><span data-stu-id="ff8d5-143">throw</span></span>](../../language-reference/keywords/throw.md)
- [<span data-ttu-id="ff8d5-144">try-catch</span><span class="sxs-lookup"><span data-stu-id="ff8d5-144">try-catch</span></span>](../../language-reference/keywords/try-catch.md)
- [<span data-ttu-id="ff8d5-145">try-finally</span><span class="sxs-lookup"><span data-stu-id="ff8d5-145">try-finally</span></span>](../../language-reference/keywords/try-finally.md)
- [<span data-ttu-id="ff8d5-146">try-catch-finally</span><span class="sxs-lookup"><span data-stu-id="ff8d5-146">try-catch-finally</span></span>](../../language-reference/keywords/try-catch-finally.md)
- [<span data-ttu-id="ff8d5-147">Özel durumlar</span><span class="sxs-lookup"><span data-stu-id="ff8d5-147">Exceptions</span></span>](../../../standard/exceptions/index.md)
